export const SECRET_SIPS_ABI = {
  address: "0x8ed0039a370e311c6469c306b41636e722242686d7f837842f56b8fa365ab36d",
  name: "secret_sips",
  friends: [],
  exposed_functions: [
    {
      name: "create_post",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::string::String", "0x1::string::String", "0x1::string::String"],
      return: [],
    },
    {
      name: "get_feed",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u64", "u64"],
      return: ["vector<0x8ed0039a370e311c6469c306b41636e722242686d7f837842f56b8fa365ab36d::secret_sips::PostView>"],
    },
    {
      name: "get_leaderboard",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u64"],
      return: ["vector<0x8ed0039a370e311c6469c306b41636e722242686d7f837842f56b8fa365ab36d::secret_sips::PostView>"],
    },
    {
      name: "get_post_by_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u64"],
      return: ["0x8ed0039a370e311c6469c306b41636e722242686d7f837842f56b8fa365ab36d::secret_sips::PostView"],
    },
    {
      name: "redeem_tokens",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "upvote_post",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
  ],
  structs: [
    {
      name: "AppData",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "posts",
          type: "vector<0x8ed0039a370e311c6469c306b41636e722242686d7f837842f56b8fa365ab36d::secret_sips::Post>",
        },
        { name: "next_post_id", type: "u64" },
      ],
    },
    {
      name: "AppObjectController",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "extend_ref", type: "0x1::object::ExtendRef" }],
    },
    {
      name: "Post",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "u64" },
        { name: "owner", type: "address" },
        { name: "title", type: "0x1::string::String" },
        { name: "content", type: "0x1::string::String" },
        { name: "image_url", type: "0x1::string::String" },
        { name: "upvotes", type: "u64" },
        { name: "earned_tokens", type: "u64" },
        { name: "redeemed_tokens", type: "u64" },
        { name: "upvoters", type: "vector<address>" },
        { name: "timestamp", type: "u64" },
      ],
    },
    {
      name: "PostView",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "u64" },
        { name: "owner", type: "address" },
        { name: "title", type: "0x1::string::String" },
        { name: "content", type: "0x1::string::String" },
        { name: "image_url", type: "0x1::string::String" },
        { name: "upvotes", type: "u64" },
        { name: "earned_tokens", type: "u64" },
        { name: "redeemed_tokens", type: "u64" },
        { name: "timestamp", type: "u64" },
      ],
    },
  ],
} as const;
